version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: coffee_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coffee_db
      MYSQL_USER: coffee_user        
      MYSQL_PASSWORD: coffee_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
